name: Deploy Images

on:
  push:
    branches:
      - main
    workflow_dispatch:
      # manual dispatch allowed

jobs:
  base:
    name: "Base: ${{ matrix.image }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - debian:bullseye
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REPOSITORY_TOKEN }}
      - env:
          IMAGE: "${{ matrix.image }}"
        run: |
          echo "IMAGE_PATH=${IMAGE//:/\/}" >> $GITHUB_ENV
      - uses: docker/build-push-action@v4
        with:
          context: ./base/${{ env.IMAGE_PATH }}/image
          file: ./base/${{ env.IMAGE_PATH }}/image/Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/team-flashbang/flashes/base/${{ matrix.image }}

  games:
    name: "Game: ${{ matrix.image }}"
    runs-on: ubuntu-latest
    needs: base
    strategy:
      fail-fast: false
      matrix:
        image:
          - valheim:vanilla
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REPOSITORY_TOKEN }}
      - env:
          IMAGE: "${{ matrix.image }}"
        run: |
          echo "IMAGE_PATH=${IMAGE//:/\/}" >> $GITHUB_ENV
      - uses: docker/build-push-action@v4
        with:
          context: ./games/${{ env.IMAGE_PATH }}/image
          file: ./games/${{ env.IMAGE_PATH }}/image/Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/team-flashbang/flashes/games/${{ matrix.image }}